CREATE TABLE `z10_DataStore`.`TaskIO` (
`SubjectId` TEXT NOT NULL ,
`DateTime_Write` DATETIME NULL DEFAULT NULL ,
`ClientTimeZone` TEXT NULL DEFAULT NULL ,
`JsonString` MEDIUMTEXT NULL DEFAULT NULL ,
PRIMARY KEY (`SubjectId`(8))) ENGINE = MyISAM;